version: 2
updates:
  # Dependências Python (requirements.txt na raiz)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "deps(pip)"
    labels: ["dependencies", "python"]

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(actions)"
    labels: ["dependencies", "ci"]
