name: Python package

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 --version
          flake8 api app --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 api app --count --exit-zero --max-complexity=10 --statistics

      - name: Type check with mypy
        env:
          PYTHONPATH: ${{ github.workspace }}/api
        run: |
          mypy --version
          mypy api

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/api
          CHATWOOT_WEBHOOK_SECRET: dummy
          OPENAI_API_KEY: dummy
          REDIS_URL: redis://localhost:6379/0
        run: |
          pytest -q
